---
driver_plugin: vagrant

driver_config:
  customize:
    memory: 1024

platforms:
- name: centos-6
  driver_config:
    box: chef/centos-6.6
    require_chef_omnibus: 11.16.2
- name: centos-7
  driver_config:
    box: chef/centos-7.0
    require_chef_omnibus: 11.16.2
- name: ubuntu-12.04
  driver_config:
    box: chef/ubuntu-12.04
    require_chef_omnibus: 11.16.2
- name: ubuntu-14.04
  driver_config:
    box: chef/ubuntu-14.04
    require_chef_omnibus: 11.16.2

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[stash_test]
  attributes: {}
- name: apache2
  run_list:
  - recipe[minitest-handler]
  - recipe[stash_test::apache2]
  attributes: {}
